version: '3.0'

services:
  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: 
      --"requirepass redis123"